export type Service = {
  slug: string;
  name: string;
  icon: string;
  tagline: string;
  price: string;
  desc: string;
  includes: string[];
};

export const SERVICES: Service[] = [
  { slug: 'electrician', name: 'Electrical Services', icon: 'ph-lightning', tagline: 'Wiring, fittings and repairs done safely.', price: 'Rs. 499', desc: 'From flickering lights to full rewiring, our licensed electricians handle switchboards, fans, MCBs, inverters and new fittings with a proper safety check on every visit.', includes: ['Fault finding and repair', 'Switch and socket replacement', 'Fan, light and MCB installation', 'Full wiring safety check'] },
  { slug: 'plumbing', name: 'Plumbing Services', icon: 'ph-wrench', tagline: 'Leaks, blocks and fittings, fixed fast.', price: 'Rs. 599', desc: 'Leaking taps, blocked drains, running cisterns or new fittings. Our plumbers bring the right tools and fix it in one visit wherever possible.', includes: ['Leak and seepage repair', 'Drain unblocking', 'Tap and pipe fitting', 'Bathroom fixture installation'] },
  { slug: 'appliance-repair', name: 'AC & Home Appliance Services', icon: 'ph-wind', tagline: 'Servicing and repair for your home appliances.', price: 'Rs. 799', desc: 'AC gas refill and servicing, washing machine drum and motor issues, fridge cooling problems. All diagnosed and repaired by trained technicians.', includes: ['AC servicing and gas refill', 'Washing machine repair', 'Refrigerator repair', 'Yearly maintenance plans'] },
  { slug: 'gardening', name: 'Gardening & Landscaping', icon: 'ph-plant', tagline: 'Lawn care, pruning and garden upkeep.', price: 'Rs. 699', desc: 'Regular mowing, hedge trimming, potting and seasonal planting to keep your garden or terrace green all year round.', includes: ['Lawn mowing and edging', 'Pruning and hedge trimming', 'Potting and planting', 'Pest and weed control'] },
  { slug: 'barber', name: 'At-Home Grooming Services', icon: 'ph-scissors', tagline: 'A proper haircut, without leaving home.', price: 'Rs. 399', desc: 'Professional haircuts, beard grooming and styling in the comfort of your home, at a time that suits you.', includes: ['Haircut and styling', 'Beard trim and shave', 'Hair spa and wash', 'Haircuts for kids'] },
  { slug: 'fruit-veg', name: 'Fresh Fruits & Vegetables', icon: 'ph-carrot', tagline: 'Fresh produce, sourced daily.', price: 'Free delivery', desc: 'Handpicked fruits and vegetables delivered fresh from your local mandi, so you never run out of the essentials.', includes: ['Daily fresh sourcing', 'Custom baskets', 'Same day delivery', 'Quality guarantee'] },
  { slug: 'pharmacy', name: 'Pharmacy & Healthcare Essentials', icon: 'ph-first-aid-kit', tagline: 'Medicine delivered, fast and discreet.', price: 'Free delivery', desc: 'Send us a prescription or just tell us what you need. Genuine medicine and healthcare essentials delivered to your door.', includes: ['Prescription orders', 'OTC and wellness essentials', 'Fast local delivery', 'Verified pharmacies only'] },
  { slug: 'grocery', name: 'Grocery & Daily Essentials', icon: 'ph-shopping-cart', tagline: 'Everyday essentials, one call away.', price: 'Free delivery', desc: 'Staples, packaged goods and household essentials picked and delivered from trusted local stores near you.', includes: ['Household staples', 'Packaged and dairy goods', 'Bulk and monthly orders', 'Same day delivery'] },
  { slug: 'water-tank-cleaning', name: 'Water Tank Cleaning & Maintenance', icon: 'ph-drop', tagline: 'Cleaner tanks for safer water at home.', price: 'Rs. 1,499', desc: 'Complete sediment removal, sanitisation and disinfection of overhead and underground tanks for cleaner, safer water.', includes: ['Sediment and sludge removal', 'Sanitisation and disinfection', 'Leak and crack check', 'Before and after report'] },
  { slug: 'solar-panel-cleaning', name: 'Solar Panel Cleaning & Maintenance', icon: 'ph-sun', tagline: 'Cleaner panels mean better output.', price: 'Rs. 1,299', desc: 'Dust and load shedding grime can cut solar output by a quarter. Our team safely cleans panels and checks connections to keep your system running well.', includes: ['Dust and grime removal', 'Panel surface inspection', 'Connection check', 'Output improvement report'] },
  { slug: 'laundry', name: 'Laundry & Garment Care', icon: 'ph-t-shirt', tagline: 'Wash, fold and iron, picked up and dropped off.', price: 'Rs. 199', desc: 'Doorstep pickup and drop for wash and fold, ironing and dry cleaning, handled with care by trained staff.', includes: ['Wash and fold', 'Ironing and steam press', 'Dry cleaning', 'Pickup and delivery'] },
  { slug: 'auto-repair', name: 'Auto Repair & Mechanical Services', icon: 'ph-gear-six', tagline: 'Trusted mechanics for car and bike issues.', price: 'Rs. 999', desc: 'Battery, brakes, oil change or a check up before a long drive. Our mechanics diagnose the issue and give you a clear estimate before starting.', includes: ['Oil and filter change', 'Battery and brake check', 'General diagnostics', 'Pickup for major repairs'] },
  { slug: 'welding', name: 'Welding & Metal Fabrication', icon: 'ph-fire-simple', tagline: 'Gates, grills and metal repairs, welded on site.', price: 'Rs. 899', desc: 'Broken gate hinges, rusted grills, balcony railings or a custom metal stand. Our welders bring their own equipment to your home and fix or fabricate it on the spot.', includes: ['Gate and grill repair', 'Railing and stand fabrication', 'Rust removal and repainting', 'On-site welding, no workshop visit'] },
  { slug: 'painter', name: 'Painting Services', icon: 'ph-paint-roller', tagline: 'Interior and exterior painting, neat and on time.', price: 'Rs. 799', desc: 'Wall painting, texture finishes and waterproofing. Our painters prep surfaces properly and protect your furniture and floors before any work begins.', includes: ['Interior and exterior painting', 'Surface prep and putty work', 'Waterproofing and texture finish', 'Furniture and floor protection'] },
  { slug: 'carpenter', name: 'Carpentry Services', icon: 'ph-hammer', tagline: 'Furniture, fittings and wood repairs at home.', price: 'Rs. 599', desc: 'Broken hinges, sticking doors, custom shelving or new furniture. Our carpenters bring their own tools and get it done on site.', includes: ['Door and window repair', 'Custom shelving and fittings', 'Furniture repair and polish', 'On-site measurement and fabrication'] },
];

export const OFFERS: Service[] = [
  { slug: 'renovation', name: 'Home Renovation', icon: 'ph-house-line', tagline: 'A full home renovation, planned from start to finish.', price: 'Free visit', desc: 'From a single room refresh to a full home overhaul. Civil work, painting, flooring, electrical and plumbing, all coordinated by one team. Start with a free visit to your home and a written quote, no obligation at all.', includes: ['Free on-site visit', 'Clear quote and timeline', 'Civil work, painting and flooring', 'One point of contact throughout'] },
  { slug: 'interior-design', name: 'Interior Designing', icon: 'ph-armchair', tagline: 'A home designed around how your family lives.', price: 'Free visit', desc: 'Modular kitchens, wardrobes, false ceilings and full interiors, from the first idea to the final installation. It starts with a free design visit at your convenience.', includes: ['Free design consultation', '3D layout and moodboard', 'Modular furniture and fittings', 'Complete turnkey execution'] },
];
